name: Frontend Test and Build

on:
  push:
    branches:
      - main  # Run tests and build on every push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/deveffect-key.pem
          chmod 600 ~/.ssh/deveffect-key.pem
          
      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Check SSH Key Permissions
        run: ls -l ~/.ssh/

      - name: Check EC2 Host
        run: echo "EC2_HOST:${{ secrets.EC2_HOST }}"

      # Build Frontend (React App)
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          ls -la ./build

      # Upload Frontend Files to EC2
      - name: Upload frontend to EC2
        run: |
          scp -v -i ~/.ssh/deveffect-key.pem -P ${{ secrets.SSH_PORT }} -r ./frontend/build/* ubuntu@${{ secrets.EC2_HOST }}:${{ secrets.FRONTEND_PATH }}

        
