name: Build and Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm i

      - name: Build frontend
        working-directory: ./frontend
        run: npm start

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm i

      - name: Build backend
        working-directory: ./backend
        run: node ./index.js

