name: Frontend Test and Build

on:
  push:
    branches:
      - main  # Run tests and build on every push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the Node.js version

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend  # Adjust this path if needed
        run: npm install  # Use npm ci for a clean install

      # Step 4: Build frontend
      - name: Build frontend
        working-directory: ./frontend  # Adjust this path if needed
        run: npm run build

      # Step 5: Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend  # Adjust this path if needed
        run: npm ci  # Clean install for CI environments

      # Step 6: Upload Frontend to AWS S3
      - name: Upload Frontend to AWS S3
        run: |
          aws s3 sync ./frontend/build s3://deveffect-blog/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 7: Upload Backend to AWS S3 (if applicable)
      - name: Upload Backend to AWS S3
        run: |
          aws s3 sync ./backend s3://deveffect-blog/static --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Optional: Run backend server (if needed for tests)
      - name: Run backend server
        working-directory: ./backend  # Adjust this path if needed
        run: |
          npm start &  # Start the backend server in the background
          sleep 5  # Wait for the server to initialize
        continue-on-error: true  # Allows the pipeline to continue if the server crashes
